In [ ]:
!pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

In [ ]:
import twint

import nest_asyncio
nest_asyncio.apply()

In [ ]:
# Create a function to scrape a user's account.
c = twint.Config()
c.Username = "elonmusk" 
c.Since = "2015-11-17"
c.Until = "2020-11-17"
c.Lang = "en"
c.Store_csv = True
c.Output = "tweets.csv"
twint.run.Search(c)

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [ ]:
!cp tweets.csv "drive/My Drive/"

In [ ]:
tweets = pd.read_csv('tweets.csv')

tweets.head()

                    id      conversation_id  ... trans_src trans_dest
0  1328458535340949505  1328428879334297600  ...       NaN        NaN
1  1328451518010327042  1328143001697230848  ...       NaN        NaN
2  1328424097110323200  1328352029190877185  ...       NaN        NaN
3  1328421992144355328  1328352029190877185  ...       NaN        NaN
4  1328419837656276992  1328338500064845825  ...       NaN        NaN

[5 rows x 36 columns]